/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;
import MODELO.Cliente;
/**
 *
 * @author robin
 */
public class frm_persona extends javax.swing.JFrame {

    /**
     * Creates new form frm_persona
     */
    Cliente obj_Cliente;
    public frm_persona() {
        super("fORMULARIO");
        initComponents();
        obj_Cliente = new Cliente();
        obj_Cliente.setNit(TXT_NIT.getText());
        this.table_datos.setModel(obj_Cliente.leer());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        EMPLEADOS = new javax.swing.JTabbedPane();
        LBLDIRECCION = new javax.swing.JPanel();
        LBLTITULO = new javax.swing.JLabel();
        LBL_NIT = new javax.swing.JLabel();
        LBL_NOMBRE = new javax.swing.JLabel();
        LBL_APELLIDO = new javax.swing.JLabel();
        LBL_DIRECCION = new javax.swing.JLabel();
        LBL_TELEFONO = new javax.swing.JLabel();
        LBL_NACIMIENTO = new javax.swing.JLabel();
        BTT_GUARDAR = new javax.swing.JButton();
        TXT_NIT = new javax.swing.JTextField();
        TXT_NOMBRE = new javax.swing.JTextField();
        TXT_APELLIDOS = new javax.swing.JTextField();
        TXT_DIRECCION = new javax.swing.JTextField();
        TXT_TELEFONO = new javax.swing.JTextField();
        TXT_NACIMIENTO = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        table_datos = new javax.swing.JTable();
        lbl_id = new javax.swing.JLabel();
        btn_actualizar = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        PANEL_EMPLEADOS = new javax.swing.JPanel();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        LBLTITULO.setText("FORMULARIO CLIENTE");

        LBL_NIT.setText("NIT");

        LBL_NOMBRE.setText("NOMBRE");

        LBL_APELLIDO.setText("APELLIDOS");

        LBL_DIRECCION.setText("DIRECCION");

        LBL_TELEFONO.setText("TELEFONO");

        LBL_NACIMIENTO.setText("NACIMIENTO");

        BTT_GUARDAR.setForeground(new java.awt.Color(0, 0, 204));
        BTT_GUARDAR.setText("GUARDAR");
        BTT_GUARDAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTT_GUARDARActionPerformed(evt);
            }
        });

        TXT_NIT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXT_NITActionPerformed(evt);
            }
        });

        table_datos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6", "ZXC"
            }
        ));
        table_datos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_datosMouseClicked(evt);
            }
        });
        table_datos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                table_datosKeyReleased(evt);
            }
        });
        jScrollPane2.setViewportView(table_datos);

        lbl_id.setText("0");

        btn_actualizar.setText("ACTUALIZAR");
        btn_actualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_actualizarActionPerformed(evt);
            }
        });

        jButton2.setText("BORRAR");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout LBLDIRECCIONLayout = new javax.swing.GroupLayout(LBLDIRECCION);
        LBLDIRECCION.setLayout(LBLDIRECCIONLayout);
        LBLDIRECCIONLayout.setHorizontalGroup(
            LBLDIRECCIONLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LBLDIRECCIONLayout.createSequentialGroup()
                .addGap(0, 51, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 613, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44))
            .addGroup(LBLDIRECCIONLayout.createSequentialGroup()
                .addGroup(LBLDIRECCIONLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(LBLDIRECCIONLayout.createSequentialGroup()
                        .addGap(245, 245, 245)
                        .addComponent(LBLTITULO))
                    .addGroup(LBLDIRECCIONLayout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addGroup(LBLDIRECCIONLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LBL_DIRECCION)
                            .addComponent(LBL_TELEFONO)
                            .addComponent(LBL_NACIMIENTO)
                            .addGroup(LBLDIRECCIONLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(LBL_NIT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(LBL_NOMBRE)
                                .addComponent(LBL_APELLIDO, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(117, 117, 117)
                        .addGroup(LBLDIRECCIONLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(LBLDIRECCIONLayout.createSequentialGroup()
                                .addComponent(BTT_GUARDAR)
                                .addGap(49, 49, 49)
                                .addComponent(btn_actualizar)
                                .addGap(43, 43, 43)
                                .addComponent(jButton2))
                            .addGroup(LBLDIRECCIONLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(TXT_NIT, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(TXT_NOMBRE)
                                .addComponent(TXT_APELLIDOS)
                                .addComponent(TXT_DIRECCION)
                                .addComponent(TXT_TELEFONO)
                                .addComponent(TXT_NACIMIENTO, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lbl_id, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        LBLDIRECCIONLayout.setVerticalGroup(
            LBLDIRECCIONLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LBLDIRECCIONLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(LBLTITULO)
                .addGap(18, 18, 18)
                .addComponent(lbl_id)
                .addGap(22, 22, 22)
                .addGroup(LBLDIRECCIONLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LBL_NIT)
                    .addComponent(TXT_NIT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(LBLDIRECCIONLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LBL_NOMBRE)
                    .addComponent(TXT_NOMBRE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(LBLDIRECCIONLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LBL_APELLIDO)
                    .addComponent(TXT_APELLIDOS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(LBLDIRECCIONLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LBL_DIRECCION)
                    .addComponent(TXT_DIRECCION, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(LBLDIRECCIONLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LBL_TELEFONO)
                    .addComponent(TXT_TELEFONO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(LBLDIRECCIONLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LBL_NACIMIENTO)
                    .addComponent(TXT_NACIMIENTO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(LBLDIRECCIONLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BTT_GUARDAR)
                    .addComponent(btn_actualizar)
                    .addComponent(jButton2))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        EMPLEADOS.addTab("CLIENTES", LBLDIRECCION);

        javax.swing.GroupLayout PANEL_EMPLEADOSLayout = new javax.swing.GroupLayout(PANEL_EMPLEADOS);
        PANEL_EMPLEADOS.setLayout(PANEL_EMPLEADOSLayout);
        PANEL_EMPLEADOSLayout.setHorizontalGroup(
            PANEL_EMPLEADOSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 708, Short.MAX_VALUE)
        );
        PANEL_EMPLEADOSLayout.setVerticalGroup(
            PANEL_EMPLEADOSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 572, Short.MAX_VALUE)
        );

        EMPLEADOS.addTab("EMPLEADOS", PANEL_EMPLEADOS);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(EMPLEADOS)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(EMPLEADOS)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TXT_NITActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXT_NITActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TXT_NITActionPerformed

    private void BTT_GUARDARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTT_GUARDARActionPerformed
        obj_Cliente =  new Cliente(0, TXT_NIT.getText(), TXT_NOMBRE.getText(), TXT_APELLIDOS.getText(), TXT_DIRECCION.getText(), TXT_TELEFONO.getText(), TXT_NACIMIENTO.getText());
        obj_Cliente.crear();
        this.table_datos.setModel(obj_Cliente.leer());
    }//GEN-LAST:event_BTT_GUARDARActionPerformed
private void select_datos(){
     int fila = table_datos.getSelectedRow();
        lbl_id.setText(table_datos.getValueAt(fila, 0).toString());
        TXT_NIT.setText(table_datos.getValueAt(fila, 1).toString());
        TXT_NOMBRE.setText(table_datos.getValueAt(fila, 2).toString());
        TXT_APELLIDOS.setText(table_datos.getValueAt(fila, 3).toString());
        TXT_DIRECCION.setText(table_datos.getValueAt(fila, 4).toString());
        TXT_TELEFONO.setText(table_datos.getValueAt(fila, 5).toString());
        TXT_NACIMIENTO.setText(table_datos.getValueAt(fila, 6).toString());
}
    private void table_datosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_datosMouseClicked
        // TODO add your handling code her
        select_datos();
    }//GEN-LAST:event_table_datosMouseClicked

    private void table_datosKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_table_datosKeyReleased
        // TODO add your handling code here:
       select_datos();
    }//GEN-LAST:event_table_datosKeyReleased

    private void btn_actualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_actualizarActionPerformed
        // TODO add your handling code here:
        obj_Cliente =  new Cliente(Integer.valueOf(lbl_id.getText()), TXT_NIT.getText(), TXT_NOMBRE.getText(), TXT_APELLIDOS.getText(), TXT_DIRECCION.getText(), TXT_TELEFONO.getText(), TXT_NACIMIENTO.getText());
        obj_Cliente.actualizar();
        this.table_datos.setModel(obj_Cliente.leer());
    }//GEN-LAST:event_btn_actualizarActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        obj_Cliente = new Cliente();
        obj_Cliente.setId(Integer.valueOf(lbl_id.getText()));
        obj_Cliente.borrar();
        table_datos.setModel(obj_Cliente.leer());
        
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frm_persona.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frm_persona.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frm_persona.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frm_persona.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frm_persona().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTT_GUARDAR;
    private javax.swing.JTabbedPane EMPLEADOS;
    private javax.swing.JPanel LBLDIRECCION;
    private javax.swing.JLabel LBLTITULO;
    private javax.swing.JLabel LBL_APELLIDO;
    private javax.swing.JLabel LBL_DIRECCION;
    private javax.swing.JLabel LBL_NACIMIENTO;
    private javax.swing.JLabel LBL_NIT;
    private javax.swing.JLabel LBL_NOMBRE;
    private javax.swing.JLabel LBL_TELEFONO;
    private javax.swing.JPanel PANEL_EMPLEADOS;
    private javax.swing.JTextField TXT_APELLIDOS;
    private javax.swing.JTextField TXT_DIRECCION;
    private javax.swing.JTextField TXT_NACIMIENTO;
    private javax.swing.JTextField TXT_NIT;
    private javax.swing.JTextField TXT_NOMBRE;
    private javax.swing.JTextField TXT_TELEFONO;
    private javax.swing.JButton btn_actualizar;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lbl_id;
    public javax.swing.JTable table_datos;
    // End of variables declaration//GEN-END:variables
}
